name: Continuous Integration

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  pylint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Python Pylin GitHub Action
      uses: fylein/python-pylint-github-action@v4
      with:
        args: pip3 install -r requirements.txt && pip install pylint-django==2.3.0 && pylint --load-plugins pylint_django --rcfile=.pylintrc **/**.py
        
  pytest:
    runs-on: ubuntu-latest
    environment: CI Environment
    steps:
      - uses: actions/checkout@v2 
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      - name: Bring up Services and Run Tests
        run: |
          docker-compose -f docker-compose-pipeline.yml build
          docker-compose -f docker-compose-pipeline.yml up -d
          docker-compose -f docker-compose-pipeline.yml exec -T api pytest tests/ --cov=. --junit-xml=test-reports/report.xml --cov-report=term-missing --cov-fail-under=90 | tee pytest-coverage.txt
          echo "STATUS=$(cat pytest-coverage.txt | grep 'Required test' | awk '{ print $1 }')" >> $GITHUB_ENV
          echo "FAILED=$(cat test-reports/report.xml | awk -F'=' '{print $5}' | awk -F' ' '{gsub(/"/, "", $1); print $1}')" >> $GITHUB_ENV
        env:
          FYLE_BASE_URL: ${{ secrets.FYLE_BASE_URL }}
          FYLE_CLIENT_ID: ${{ secrets.FYLE_CLIENT_ID }}
          FYLE_CLIENT_SECRET: ${{ secrets.FYLE_CLIENT_SECRET }}
          FYLE_TOKEN_URI: ${{ secrets.FYLE_TOKEN_URI }}
          FYLE_REFRESH_TOKEN: ${{ secrets.FYLE_REFRESH_TOKEN }}
          NS_ACCOUNT_ID: ${{ secrets.NS_ACCOUNT_ID }}
          NS_CONSUMER_KEY: ${{ secrets.NS_CONSUMER_KEY }}
          NS_CONSUMER_SECRET: ${{ secrets.NS_CONSUMER_SECRET }}
          NS_TOKEN_ID: ${{ secrets.NS_TOKEN_ID }}
          NS_TOKEN_SECRET: ${{ secrets.NS_TOKEN_SECRET }}
      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        if: ${{ always() && github.ref != 'refs/heads/master' }}
        with:
          create-new-comment: true
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./test-reports/report.xml
      - name: Stop Services
        run: docker compose -f docker-compose-pipeline.yml down
      - name: Evaluate Coverage
        if: if: ${{ (env.STATUS == 'FAIL') || (env.FAILED > 0) }}
        run: exit 1
        if: env.FAILED > 0
        run: exit 1
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        if: ${{ always() && github.ref != 'refs/heads/master' }}
        env:
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: pytest job status - ${{ job.status }}
          SLACK_TITLE: Pytest Run Stats
          SLACK_ICON_EMOJI: ":terminator:"
          SLACK_USERNAME: Gandalf
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_FOOTER: ''